### ISSUE TITLE
Taipan 2.1.487.19 Update Error

### ISSUE THREAD

**Issue by elbae** [enkomio/Taipan#12]
```
PS C:\tools\Taipan\TaipanPro> .\TaipanUpdater.exe

Unhandled Exception: System.TypeInitializationException: The type initializer for 'ES.Taipan.Program' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$TaipanUpdater>.$Program' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at ES.Fslog.Compose.build(LogSourceBuilder logBuilder)
   at <StartupCode$TaipanUpdater>.$Program..cctor()
   --- End of inner exception stack trace ---
   at ES.Taipan.Program..cctor()
   --- End of inner exception stack trace ---
   at ES.Taipan.Program.main(String[] argv)
```

**Comment by enkomio** [comment]
Hi @elbae,

Is it the Pro Edition, right?

**Comment by enkomio** [comment]
We are investigating an issue very similar to this one. Could you please try to download the Updater in a new folder and install Taipan from a clean state?

**Comment by elbae** [comment]
Yes, I'm gonna try.

**Comment by elbae** [comment]
It worked, thanks.

**Comment by enkomio** [comment]
Great. 

This is a know issue that is due to the usage of different library versions. I'm working on this, but until a fix is out I suggest to install the software from a clean directory.
